apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-app
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: sample-app-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50