apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  labels:
    app: sample-app
spec:
  type: ClusterIP
  selector:
    app: sample-app
  ports:
    - name: svc-port
      port: 80
      targetPort: app-port
      protocol: TCP
